### ISSUE TITLE
Implement Data Visualization Technique

### ISSUE THREAD

**Issue by donnell794** [MaxMcGlinnPoole/TermDocumentTensor#10]
Max doesn't seem to think the heat map is great at visualizing the relationships in the data. Are there any ideas as to another way to show these relationships visually?

**Comment by MaxMcGlinnPoole** [comment]
I'm working on this in this branch right now: https://github.com/MaxMcGlinnPoole/TermDocumentTensor/tree/Visualization-Improvement

I got a better heat-map. Right now I am looking into using K-means clustering techniques. I am using the resource here to learn more about it: http://scikit-learn.org/stable/modules/clustering.html#k-means

I encourage other people to look into this as well.

**Comment by MaxMcGlinnPoole** [comment]
We now have a data visualization technique in the kmeans scatter plot. 

There are other ways to visualize this data that may be useful to implement in the future. If those types of visualization are to be added, they should be given their own issue.
