### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by donnell794** [MaxMcGlinnPoole/TermDocumentTensor#12]
Do you guys have any comments about the current state of the README? Things that can/should be added or removed, things that can be changed, etc etc

**Comment by MaxMcGlinnPoole** [comment]
It should have a section for command args explanation once those are added.

It might be nice to include a warning about the zeus_binaries, they shouldn't be dangerous but I think a virus scan would pick them up.

You can remove the section about contributing, that is explained in the Github documentation.
I guess keeping it around to share with Sumanth if he needs it might be okay (not sure his experience with Git?) but having it as part of the main repo is not necessary.

Also replace the line "NSF" with some more substantial thanks to the NSF for funding.

**Comment by donnell794** [comment]
i think this issue will stay open as there is going to be a continuous need to update the readme — all have been assigned to this issue. if that's a problem, this can be closed and reopened whenever necesary

**Comment by MaxMcGlinnPoole** [comment]
This should be done with the recent command line argument updates
