### ISSUE TITLE
Include Legend for Heat map

### ISSUE THREAD

**Issue by donnell794** [MaxMcGlinnPoole/TermDocumentTensor#15]
Until we discover that another visualization technique is viable, we need to improve what we have now and that means making the heat map more readable — a legend is necessary.

**Comment by donnell794** [comment]
`
plt.colorbar(heatmap)
`
this seems to be the correct way of doing so. Mutators can be easily googled once you have that tidbit

**Comment by MaxMcGlinnPoole** [comment]
Sure, maybe this is something you can tackle?

**Comment by donnell794** [comment]
heat map has been completed. all other visual enhancements can be completed in another issue
