### ISSUE TITLE
Unleveled Heat Map Blocks at Axis 

### ISSUE THREAD

**Issue by donnell794** [MaxMcGlinnPoole/TermDocumentTensor#23]
<img width="594" alt="heatmap" src="https://user-images.githubusercontent.com/11854190/31855645-18d93fac-b67d-11e7-82a8-2a422ae7f5a3.png">

the blocks are a bit off-center in that at the axis, there's a slight shift. am not sure what is causing this issue but will look into fixing it

**Comment by MaxMcGlinnPoole** [comment]
Fixed by Donnell in #24
